config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'homepage/index'
  root to: 'homepage#index', as: 'homepage'

  resources :flats
  resources :users
  resources :tenants, only: %i[create destroy]
  resources :neighborhoods


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/flat.rb
# frozen_string_literal: true

class Flat < ApplicationRecord
  has_many :tenants, dependent: :destroy
  belongs_to :neighborhood, optional: true, foreign_key: :neighborhood_id
  validates :name, presence: true
  validates :latitude, presence: true
  validates :longitude, presence: true
  
  # This is draft AREL and SQL code for condition 'belongs_to'
  #
  #  lambda {
  #   where('SELECT "neighborhood_id".* FROM "neighborhoods" WHERE
  #     (SELECT "neighborhoods"."maxlat", "neighborhoods"."minlat", "neighborhoods"."maxlong", "neighborhoods"."minlong"
  #        FROM "neighborhoods" UNION ALL SELECT "flats"."latitude", "flats"."longitude" FROM "flats"
  #     "flats"."latitude" < "neighborhoods"."maxlat" AND "flats"."latitude" > "neighborhoods"."minlat"
  #     AND "flats"."longitude" < "neighborhoods"."maxlong" AND "flats"."longitude" > "neighborhoods"."minlong")')
  #                             }

  # Neighborhood.where(flats(Arel.star).join(neighborhoods).where('flats.latitude > neighborhoods.minlat and flats.latitude < neighborhoods.maxlat and
  #   flats.longitude > neighborhoods.minlong and flats.longitude < neighborhoods.maxlong'))

end

app/controllers/flats_controller.rb
# frozen_string_literal: true

class FlatsController < ApplicationController
  before_action :set_flat, only: %i[show edit update destroy]

  # GET /flats or /flats.json
  def index
    @flats = Flat.all
  end

  # GET /flats/1 or /flats/1.json
  def show; end

  # GET /flats/new
  def new
    @flat = Flat.new
  end

  # GET /flats/1/edit
  def edit; end

  # POST /flats or /flats.json
  def create
    @flat = Flat.new(flat_params)

    respond_to do |format|
      if @flat.save
        format.html { redirect_to request.referrer || flat_url(@flat), notice: 'Flat was successfully created.' }
        format.json { render :show, status: :created, location: @flat }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @flat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flats/1 or /flats/1.json
  def update
    respond_to do |format|
      if @flat.update(flat_params)
        format.html { redirect_to flat_url(@flat), notice: 'Flat was successfully updated.' }
        format.json { render :show, status: :ok, location: @flat }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @flat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flats/1 or /flats/1.json
  def destroy
    @flat.destroy

    respond_to do |format|
      format.html { redirect_to flats_url, notice: 'Flat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_flat
    @flat = Flat.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def flat_params
    params.require(:flat).permit(:name, :latitude, :longitude)
  end

end

app/helpers/flats_helper.rb
# frozen_string_literal: true

module FlatsHelper
end

app/views/flats/_flat.html.erb
<div id="<%= dom_id flat %>">
  <p>
    <strong>Name:</strong>
    <%= flat.name %>
  </p>

  <p>
    <strong>Latitude:</strong>
    <%= flat.latitude %>
  </p>

  <p>
    <strong>Longitude:</strong>
    <%= flat.longitude %>
  </p>

</div>

app/views/flats/_form.html.erb
<%= form_with(model: flat) do |form| %>
  <% if flat.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(flat.errors.count, "error") %> prohibited this flat from being saved:</h2>

      <ul>
        <% flat.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :latitude, style: "display: block" %>
    <%= form.text_field :latitude %>
  </div>

  <div>
    <%= form.label :longitude, style: "display: block" %>
    <%= form.text_field :longitude %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/flats/edit.html.erb
<h1>Editing flat</h1>

<%= render "form", flat: @flat %>

<br>

<div>
  <%= link_to "Show this flat", @flat %> |
  <%= link_to "Back to flats", flats_path %>
</div>

app/views/flats/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Flats</h1>

<div id="flats">
  <% @flats.each do |flat| %>
    <%= render flat %>
    <p>
      <%= link_to "Show this flat", flat %>
    </p>
  <% end %>
</div>

<%= link_to "New flat", new_flat_path %>

app/views/flats/new.html.erb
<h1>New flat</h1>

<%= render "form", flat: @flat %>

<br>

<div>
  <%= link_to "Back to flats", flats_path %>
</div>

app/views/flats/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @flat %>

<div>
  <%= link_to "Edit this flat", edit_flat_path(@flat) %> |
  <%= link_to "Back to flats", flats_path %>

  <%= button_to "Destroy this flat", @flat, method: :delete %>
</div>