config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'homepage/index'
  root to: 'homepage#index', as: 'homepage'

  resources :flats
  resources :users
  resources :tenants, only: %i[create destroy]
  resources :neighborhoods


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/neighborhood.rb
# frozen_string_literal: true

class Neighborhood < ApplicationRecord
  has_many :flats, dependent: :destroy
  validates :maxlat, presence: true
  validates :minlat, presence: true
  validates :maxlong, presence: true
  validates :maxlong, presence: true
end

app/controllers/neighborhoods_controller.rb
# frozen_string_literal: true

class NeighborhoodsController < ApplicationController
  before_action :set_neighborhood, only: %i[show edit update destroy]

  # GET /neighborhoods or /neighborhoods.json
  def index
    @neighborhoods = Neighborhood.all
  end

  # GET /neighborhoods/1 or /neighborhoods/1.json
  def show; end

  # GET /neighborhoods/new
  def new
    @neighborhood = Neighborhood.new
  end

  # GET /neighborhoods/1/edit
  def edit; end

  # POST /neighborhoods or /neighborhoods.json
  def create
    @neighborhood = Neighborhood.new(neighborhood_params)

    respond_to do |format|
      if @neighborhood.save
        format.html { redirect_to neighborhood_url(@neighborhood), notice: 'Neighborhood was successfully created.' }
        format.json { render :show, status: :created, location: @neighborhood }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @neighborhood.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /neighborhoods/1 or /neighborhoods/1.json
  def update
    respond_to do |format|
      if @neighborhood.update(neighborhood_params)
        format.html { redirect_to neighborhood_url(@neighborhood), notice: 'Neighborhood was successfully updated.' }
        format.json { render :show, status: :ok, location: @neighborhood }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @neighborhood.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /neighborhoods/1 or /neighborhoods/1.json
  def destroy
    @neighborhood.destroy

    respond_to do |format|
      format.html { redirect_to neighborhoods_url, notice: 'Neighborhood was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_neighborhood
    @neighborhood = Neighborhood.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def neighborhood_params
    params.require(:neighborhood).permit(:name, :maxlat, :minlat, :maxlong, :minlong)
  end
end

app/helpers/neighborhoods_helper.rb
# frozen_string_literal: true

module NeighborhoodsHelper
end

app/views/neighborhoods/_form.html.erb
<%= form_with(model: neighborhood) do |form| %>
  <% if neighborhood.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(neighborhood.errors.count, "error") %> prohibited this neighborhood from being saved:</h2>

      <ul>
        <% neighborhood.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :maxlat, style: "display: block" %>
    <%= form.text_field :maxlat %>
  </div>

  <div>
    <%= form.label :minlat, style: "display: block" %>
    <%= form.text_field :minlat %>
  </div>

  <div>
    <%= form.label :maxlong, style: "display: block" %>
    <%= form.text_field :maxlong %>
  </div>

  <div>
    <%= form.label :minlong, style: "display: block" %>
    <%= form.text_field :minlong %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/neighborhoods/_neighborhood.html.erb
<div id="<%= dom_id neighborhood %>">
  <p>
    <strong>Name:</strong>
    <%= neighborhood.name %>
  </p>

  <p>
    <strong>Maxlat:</strong>
    <%= neighborhood.maxlat %>
  </p>

  <p>
    <strong>Minlat:</strong>
    <%= neighborhood.minlat %>
  </p>

  <p>
    <strong>Maxlong:</strong>
    <%= neighborhood.maxlong %>
  </p>

  <p>
    <strong>Minlong:</strong>
    <%= neighborhood.minlong %>
  </p>

</div>

app/views/neighborhoods/edit.html.erb
<h1>Editing neighborhood</h1>

<%= render "form", neighborhood: @neighborhood %>

<br>

<div>
  <%= link_to "Show this neighborhood", @neighborhood %> |
  <%= link_to "Back to neighborhoods", neighborhoods_path %>
</div>

app/views/neighborhoods/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Neighborhoods</h1>

<div id="neighborhoods">
  <% @neighborhoods.each do |neighborhood| %>
    <%= render neighborhood %>
    <p>
      <%= link_to "Show this neighborhood", neighborhood %>
    </p>
  <% end %>
</div>

<%= link_to "New neighborhood", new_neighborhood_path %>

app/views/neighborhoods/new.html.erb
<h1>New neighborhood</h1>

<%= render "form", neighborhood: @neighborhood %>

<br>

<div>
  <%= link_to "Back to neighborhoods", neighborhoods_path %>
</div>

app/views/neighborhoods/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @neighborhood %>

<div>
  <%= link_to "Edit this neighborhood", edit_neighborhood_path(@neighborhood) %> |
  <%= link_to "Back to neighborhoods", neighborhoods_path %>

  <%= button_to "Destroy this neighborhood", @neighborhood, method: :delete %>
</div>