config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'homepage/index'
  root to: 'homepage#index', as: 'homepage'

  resources :flats
  resources :users
  resources :tenants, only: %i[create destroy]
  resources :neighborhoods


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <div class="container">
        <%= link_to "Home", homepage_path, id: "logo" %>
        <nav>
            <ul class="nav navbar-nav collapse navbar-collapse justify-content-start"
            id="navbarSupportedContent">
                <li class="nav-item"><a class="nav-link active" aria-current="page">
                    <%= link_to "Users", users_path, id: "menu_button" %></a>
                </li>
                <li class="nav-item"><a class="nav-link">
                    <%= link_to "Flats", flats_path, id: "menu_button" %></a>
                </li>
                <li class="nav-item"><a class="nav-link">
                    <%= link_to "Neighborhoods", neighborhoods_path, id: "menu_button" %></a>
                </li>
            </ul>
        </nav>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Technical Challenge</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", media: "all", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>
  <body>
    <%= render 'layouts/header' %>
      <%= yield %>
    </div>
  </body>
</html>